ARG ROS_DISTRO=jazzy
FROM gitlab-extern.atb-potsdam.de:5050/am/ros/apps/app_template/build AS build
FROM gitlab-extern.atb-potsdam.de:5050/am/ros/utils/ros_base_containers/${ROS_DISTRO}-ros-core

# Install dependencies
RUN apt update && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
COPY --from=build /workspace/install /workspace/install

# Add source to bashrc
RUN echo "source /workspace/install/setup.bash" >> ~/.bashrc
COPY ros_entrypoint.sh /ros_entrypoint.sh
RUN chmod +x /ros_entrypoint.sh
ENTRYPOINT [ "/ros_entrypoint.sh" ]